### ISSUE TITLE
Need help implementing rolling hash

### ISSUE THREAD

**Issue by AritroSaha10** [JFSS-CS-Club/senior-scholars#2]
**Language**
C++

**Describe the issue**
Right now, I'm trying S3 on CCC 2020. I've gotten most of the details down (using a frequency chart to see if it's a permutation, shifting this frequency chart instead of recalculating every iteration, using hashing to store previous permutations instead of storing the string). 

Since I'm getting TLE on Batch 4 Case 30, I'm trying to implement a rolling hash instead of recalculating it every iteration. However, the result from my rolling hash code doesn't seem to match up with the result from just recalculating the hash. This causes my current rolling hash code to fail on the fourth test case, likely because it is translating the string into an incorrect hash.

How can I fix my current code in order to properly implement a rolling hash?

**Code Sample**
DMOJ Link for my code without rolling hash: https://dmoj.ca/submission/3309847
repl.it link for my code without rolling hash: https://repl.it/@AS08FM/S3CodeWithoutRollingHash#main.cpp

DMOJ Link for my code with rolling hash: https://dmoj.ca/submission/3310049
repl.it link for my code with rolling hash: https://repl.it/@AS08FM/S3CodeWithRollingHash#main.cpp

**To Reproduce**
Steps to reproduce the behavior (if applicable):
For code without rolling hash:
1. Run on DMOJ (test case too large to use in repl.it)

For code with rolling hash:
1. Run code
2. Use this input:
```
vvzzzzzv
ikmbzzzzzvzvzvwygnwvdvvzvzzzzbpxvzzzvzvzvszzzvzvzvpbozzzvzvzvicvzvzzzvzdauwipnxlqccvzvvzzzzggezzzvzvzvbifrvdzvzzzzzvvzzvzzzzjucwoaufozvvzzzvzfmriovjcvzzvvzzzystdyzfzzvvzvzzogqjvzvzzzzvmigydrbxzzvzvzzv
```

**Expected behavior**
Rolling hash produces same hash as just using hash function. 

**Screenshots**
Proof of rolling hash not producing same the same result as just using the hash function:
![image](https://user-images.githubusercontent.com/29025984/105442611-f77c3080-5c37-11eb-8292-5d68b4f9be07.png)

Note: `definiteHash` is the hash calculated from running `rollingHash()`, and `currentHash` uses the rolling hash code I have right now.

**Additional notes**
I believe I added most of the info in the description but please let me know if there's any details I missed so I can add it in.

**Comment by davidli3100** [comment]
Thanks for filing an issue! I've assigned our lead instructors for the competitive programming unit so they can take a look at your issue and provide feedback.

**Comment by AritroSaha10** [comment]
Hi!

I've been working on these for the past 2 days, and have finally fixed it (at least I think). Basically, if I understood correctly, my method of implementing a rolling hash was incorrect was because it wasn't able to calculate the previous value correctly. 

I wasn't able to find a way to correctly do this, so I just resorted to making two arrays that store the hash and the powers which are run through the haystack string. After doing that, substring hashes are found by getting the subhash from the haystack hash.  This way, I'm able to get the proper subhashes. However, I'm not sure if this is the correct way since there are two 32-bit integer arrays of size 200000.

I also rearranged the main for loop in order to not use as many if statements as before (previous for loop was arranged a bit weirdly imo). 

I'm not sure if this is the most optimal code or anything, but I've added comments in case if anyone would like to see my final code:

repl.it link: https://repl.it/@AS08FM/ProperS3#main.cpp
DM::OJ link: https://dmoj.ca/submission/3318805
```
#include <bits/stdc++.h>

using namespace std;

// Arrays for the frequency charts
// std::array is used because you can use equality operator
array<int, 26> needleFrequency;
array<int, 26> substrFrequencies;

// The first array stores each hash and the second array stores the powers
// Size is 200,001 because input size is 200,000
size_t hsh[200001];
size_t pw[200001] = {1};

// This is the power that is used for hashing
const int powerBase = 31;

// Counter for the distinct permutations
int distinctPermutations = 0;

// All known hashes as a map, could also use an unordered set and get the size as the output
map<size_t, bool> knownHashes;

// Get subsection of hash and multiply by power to get the subhash
size_t getSubHash(int left, int right) {
    return hsh[right] - hsh[left - 1] * pw[right - left + 1];
}

int main() {
    // Input optimization
    ios::sync_with_stdio();
    cin.tie();
    cout.tie();

    // Input gathering    
    string n;
    string h;
    cin >> n >> h;

    // Prepare the frequency chart for the needle string
    for (char c : n) {
        needleFrequency[c - 'a']++;
    }

    // Generate full hash array for all of haystack string
    // Uses addition since it's faster
    // Example of the arrays:
    // h = "abcd"
    // hsh = [0, 1, 31 + 2, 1023 + 3, 31806 + 4]
    // pw = [1, 31, 31^2, 31^3, 31^4]
    for (int i = 0; i < h.size(); i++) {
        hsh[i + 1] = hsh[i] * powerBase + h[i];
        pw[i + 1] = pw[i] * powerBase;
    }

    for (int i = 0; i < h.size(); i++) {
        // Add to extend the frequency array window one to the right
        substrFrequencies[h[i] - 'a']++;

        // Make sure substring frequency chart is completed before shifting
        if (i + 1 < n.size()) continue;
        
        // Subtract to shorten the frequency array window one to the right, completing the shift of the window
        if (i + 1 > n.size()) substrFrequencies[h[i - n.size()] - 'a']--;

        // Checks whether the frequency arrays are the same
        // If so, generates the subhash from the hash and power array and checks if it is distinct
        if (substrFrequencies == needleFrequency) {
            size_t subhash = getSubHash(i - n.size() + 2, i + 1);
            if (!knownHashes[subhash]) {
                knownHashes[subhash] = true;
                distinctPermutations++;
           }
        }

    }

    // Output
    cout << distinctPermutations << "\n";

    return 0;
}
```

I'm not sure how to avoid further collisions in the 5th batch for DM::OJ. I believe that I'd need to make another rolling hash and then check whether the two hashes are the same to avoid collisions, but am not sure how to implement this. However, since the original problem was solved, I'll close this problem.
